package com.irononetech.android.formcomponent.view;

public enum PossibleDRMapping {
	// Original List
	/*
	BLOWER("BLOWER",0),
	HEATER("HEATER",1),
	COOLER("COOLER",2),
	WIPERMOTOR("WIPERMOTOR",3),
	WIPERARMSET("WIPERARMSET",4),
	SAVECYLINDER("SAVECYLINDER",5),
	BRAKEMASTERPUMP("BRAKEMASTERPUMP",6),
	CLUTCHPUMP("CLUTCHPUMP",8),
	DASHBOARDINNERPARTS("DASHBOARDINNERPARTS",7),
	ACCONDENSIOR("ACCONDENSIOR",9),
	RADIATOR("RADIATOR",10),
	RADIATORFAN("RADIATORFAN",11),
	ENGINEMOUNT("ENGINEMOUNT",12),
	GEARBOXMOUNT("GEARBOXMOUNT",13),
	PROLERSHAFT("PROLERSHAFT",14),
	FRONTAXIALBAR("FRONTAXIALBAR",15),
	CHASIS("CHASIS",16),
	STEERINGPUMP("STEERINGPUMP",17),
	STEERINGBOX("STEERINGBOX",18),
	TIERODSET("TIERODSET",19),
	CVJOUNT("CVJOUNT",20),
	CENTERLINK("CENTERLINK",21),
	DRAGELINK("DRAGELINK",22),
	THREEWHEELERFORK("THREEWHEELERFORK",23),
	SHOCKABSORBER("SHOCKABSORBER",24),
	BEARINGS("BEARINGS",25),
	STUBAXIAL("STUBAXIAL",26),
	LEAFSPRINGS("LEAFSPRINGS",27),
	MOTORCYCLEFORKTUBE("MOTORCYCLEFORKTUBE",28),
	TROD("TROD",29),
	HBRACKECT("HBRACKECT",30),
	CHASISFRAME("CHASISFRAME",31),
	ALLOYWHEELS("ALLOYWHEELS",32),
	STARTORMOTOR("STARTORMOTOR",33),
	ALTERNATOR("ALTERNATOR",34),
	WATERPUMP("WATERPUMP",35),
	LOWERARM("LOWERARM",36),
	UPPERARM("UPPERARM",37);*/
	
	// This is the sorted list
	ACCONDENSIOR("AC CONDENSIOR",9),
	ACCOPRESSIOR("AC COPRESSIOR",41),           /**/
	ALLOYWHEELS("ALLOY WHEELS",32),
	ALTERNATOR("ALTERNATOR",34),
	BEARINGS("BEARINGS",25),
	BLOWER("BLOWER",0),
	BRAKEMASTERPUMP("BRAKE MASTER PUMP",6),
	CENTERLINK("CENTER LINK",21),
	CHASIS("CHASIS",16),
	CHASISFRAME("CHASIS FRAME",31),
	CLUTCHPUMP("CLUTCH PUMP",8),
	COOLER("COOLER",2),
	CVJOUNT("CV JOUNT",20),
	DASHBOARDINNERPARTS("DASH BOARD INNER PARTS",7),
	DRAGELINK("DRAG LINK",22),
	ENGINEINNERPARTS("ENGINE INNER PARTS",38),  /**/
	ENGINEMOUNT("ENGINE MOUNT",12),
	FRONTAXIALBAR("FRONT AXIAL BAR",15),
	GEARBOXMOUNT("GEAR BOX MOUNT",13),
	HBRACKECT("H BRACKECT",30),
	HEADLIGHTBRACKET("HEAD LIGHT BRACKET",39),  /**/
	HEATER("HEATER",1),
	HYDROULICJACK("HYDROULIC JACK",40),         /**/
	LEAFSPRINGS("LEAF SPRING",27),
	LOWERARM("LOWER ARM",36),
	MOTORCYCLEFORKTUBE("MOTOR CYCLE FORK TUBE",28),
	PROLERSHAFT("PROPLER SHAFT",14),
	RADIATOR("RADIATOR",10),
	RADIATORFAN("RADIATOR FAN",11),
	SAVECYLINDER("SEAVE CYLINDER",5),
	SHOCKABSORBER("SHOCKABSORBER",24),
	STARTORMOTOR("STARTOR MOTOR",33),
	STEERINGBOX("STEERING BOX",18),
	STEERINGPUMP("STEERING PUMP",17),
	STUBAXIAL("STAB AXIAL",26),
	THREEWHEELERFORK("THREE WHEEL FORK",23),
	TIERODSET("TIE ROD SET",19),
	TROD("T ROD",29),
	UPPERARM("UPPER ARM",37),
	WATERPUMP("WATER PUMP",35),
	WIPERARMSET("WIPER ARM SET",4),
	WIPERMOTOR("WIPER MOTOR",3);

  
	private final String a;
	private final int b;
	PossibleDRMapping(String a, int b){
		this.a = a;
		this.b = b;
	}
	
	public String getString(){
		return this.a;
	}

	public int getInt() {
		return this.b;
	}
}
